### ISSUE TITLE
(bare global) parseFloat and parseInt fail silently

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl#642]
I remember running into this last year sometime and just finding a workaround, but it seems weird and (perhaps) common enough to address at some point. When you use either `parseFloat` or `parseInt` on the command-line, your program immediately terminates with no error or output. When you use them in the browser, the program keeps running indefinitely with no error or output. The ES6 version works, however.

```
var a = "1.2345"
console.log(typeof a) // => string
console.log(typeof Number.parseFloat(a)) // => number 
console.log(typeof parseFloat(a)) 
console.log("foobar") // doesn't run
```

**Comment by stuhlmueller** [comment]
It sounds like this is because all calls to primitive functions need to use dot notation, otherwise the function gets passed the continuation (etc) and is expected to call it:

~~~~
var obj = {
  parseFloat: parseFloat
}

obj.parseFloat("1.23")  // works
~~~

**Comment by stuhlmueller** [comment]
I agree that this is counter-intuitive and should be fixed as part of #358.

**Comment by null-a** [comment]
Closing this since it's a known issue, we have a work-around, and we intend to address it with #358.

**Comment by fredcallaway** [comment]
I think this issue should be reopened. It's been almost a year and #358 has still not come through, so it seems worthwhile to apply a quick patch. This is working for me.
```js
var parseInt = function(x) {
  return _.parseInt(x)
};
```

This was really frustrating to run into when I first started using webppl, and I'm here now because I forgot about this quirk and wasted another 15 minutes debugging before identifying the issue.

**Comment by null-a** [comment]
@fredcallaway Thanks for this. My sense is that a overhaul of the FFI (#358) is unlikely to happen soon, so I agree that it's worth considering whether there are any simple steps we can take to improve things.

Adding wrappers for `parseInt` and `parseFloat` could help, though I'm a bit worried that it has the potential to cause confusion, by giving users the impression that JS functions can be called using something other than a member expression. e.g. If a user runs into trouble calling  `RegExp` (say), having successfully called `parseInt`, I think we've given them an even harder problem to debug than they would have had otherwise.

So, rather than wrapping the JS functions, I wonder if we should add functions that shadow the JS functions and generate an error when called. This gives us an opportunity to let users know that interacting with JS isn't seamless, which might help the user avoid other interoperability issues that this change wouldn't catch. We might also consider extending this to cover more of the builtin/global JS functions than just `parseInt`/`parseFloat`. (Perhaps these could be generated dynamically by looking at `global`?)

Another thing we should do is add something about the current FFI to docs.webppl.org.

**Comment by fredcallaway** [comment]
> add functions that shadow the JS functions and generate an error when called
I think this is the best short term solution.

> add something about the current FFI to docs.webppl.org.
Also this.

I'm not sure if this is the same issue, but it's not obviously as simple as "member expressions work"
```js
var o = {
    parseInt(x) {_.parseInt(x)}
}
console.log(map(o.parseInt, ['1', '2', '3']))  // works
console.log(map(_.parseInt, ['1', '2', '3']))  // silent failure
```

**Comment by stuhlmueller** [comment]
> I'm not sure if this is the same issue, but it's not obviously as simple as "member expressions work"

Yes, tracking this in issue #30.
